#!/bin/bash

sudo apt install -y cmake build-essential pkg-config libpthread-stubs0-dev make lua5.1 unzip libtool gettext fd-find xclip luarocks flatpak

sudo apt install -y compton curl htop golang lsof i3 ccache ninja-build python3-pip dconf-editor moreutils clangd

sudo apt install -y libxcb-keysyms1-dev libxcb-keysyms1 libqt5svg5-dev libqt5x11extras5-dev x11-utils libvulkan-dev vulkan-validationlayers-dev spirv-tools

sudo apt install -y clang clangd clang-19

sudo apt install -y picom
 

