#!/bin/bash


version="v0.11.0"
if [ ! -z $NVIM_VERSION ]; then
    version="$NVIM_VERSION"
fi

echo "version: \"$version\""

# neovim btw
if [ ! -d $HOME/neovim ]; then
    	git clone https://github.com/neovim/neovim.git $HOME/neovim
    	curl -fsSL https://apt.fury.io/wez/gpg.key | sudo gpg --yes --dearmor -o /usr/share/keyrings/wezterm-fury.gpg
	echo 'deb [signed-by=/usr/share/keyrings/wezterm-fury.gpg] https://apt.fury.io/wez/ * *' | sudo tee /etc/apt/sources.list.d/wezterm.list
	sudo chmod 644 /usr/share/keyrings/wezterm-fury.gpg

fi


# wget https://luarocks.org/releases/luarocks-3.11.1.tar.gz
# tar zxpf luarocks-3.11.1.tar.gz
# cd luarocks-3.11.1
# ./configure && make && sudo make install
# sudo luarocks install luasocket
# luarocks install luacheck
